# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 07:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='')),
                ('question_type', models.CharField(choices=[('mcq_single', 'MCQ with single option correct'), ('mcq_multiple', 'MCQ with one or more options correct')], max_length=255)),
                ('option_a', models.TextField(default='')),
                ('option_b', models.TextField(default='')),
                ('option_c', models.TextField(default='')),
                ('option_d', models.TextField(default='')),
                ('option_a_correct', models.BooleanField(default=False)),
                ('option_b_correct', models.BooleanField(default=False)),
                ('option_c_correct', models.BooleanField(default=False)),
                ('option_d_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField(default='')),
                ('order_index', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'question',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='collection', max_length=300)),
                ('description', models.TextField(default='')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('private', models.BooleanField(default=False)),
                ('blacklist', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'db_table': 'quiz',
                'ordering': ['-views'],
            },
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.QuizModel'),
        ),
    ]
