# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='slug',
            field=models.SlugField(default='quiz', max_length=300),
        ),
    ]
