# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20170930_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
