# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_collections', '0005_auto_20170929_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionitemmodel',
            options={'ordering': ['-order_index'], 'verbose_name': 'Collection Item', 'verbose_name_plural': 'Collection Items'},
        ),
        migrations.AddField(
            model_name='collectionitemmodel',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collectionmodel',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
