# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_collections', '0006_auto_20170930_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionmodel',
            name='slug',
            field=models.SlugField(default='collection'),
        ),
    ]
