# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_collections', '0007_collectionmodel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionmodel',
            options={'ordering': ['-views'], 'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
    ]
