# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_collections', '0008_auto_20170930_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmodel',
            name='slug',
            field=models.SlugField(default='collection', max_length=300),
        ),
    ]
