# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('url', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stream_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stream Item',
                'verbose_name_plural': 'Stream Items',
                'db_table': 'stream_item',
            },
        ),
        migrations.CreateModel(
            name='StreamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('private', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_streams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stream',
                'verbose_name_plural': 'Streams',
                'db_table': 'stream',
            },
        ),
        migrations.AddField(
            model_name='streamitemmodel',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_streams.StreamModel'),
        ),
    ]
