# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_streams', '0005_auto_20170929_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streamitemmodel',
            options={'ordering': ['-created_on'], 'verbose_name': 'Stream Item', 'verbose_name_plural': 'Stream Items'},
        ),
        migrations.AddField(
            model_name='streamitemmodel',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='streammodel',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
