# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_streams', '0007_streammodel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streammodel',
            options={'ordering': ['-views'], 'verbose_name': 'Stream', 'verbose_name_plural': 'Streams'},
        ),
    ]
